### ISSUE TITLE
Working on the same thing

### ISSUE THREAD

**Issue by smartinov** [pkesc/prometheus_lighthouse_exporter#1]
Hi! Just wanted to mention that basically, we're working on the same thing and if you have any suggestions or something that was missing on pagespeed_exporter (https://github.com/foomo/pagespeed_exporter) feel free to ask! 

Great work by the way!

**Comment by pkesc** [comment]
Hi. I know the Pagespeed Exporter and i also used it bevor. I really like it and there are now Feature i was missing. The reason why i created the Lighthouse Exporter is because the results i get from Pagespeed are different from my local Lighthouse tests. My local Results are more realistic to actually tests on device with for example 3G.

I currently have some Problems with my Exporter because Lighthouse is build to only run on test at a time. So there is some work todo that it runs perfectly.

And thanks that you like my work!
